### ISSUE TITLE
Bug in newest version

### ISSUE THREAD

**Issue by Wassini** [J-Lindvig/Flagdays_DK#2]
This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/flagdays_dk/__init__.py:41
Integration: FlagDays DK (documentation, issues)
First occurred: 12:19:50 (1 occurrences)
Last logged: 12:19:50

Error during setup of component flagdays_dk
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/flagdays_dk/__init__.py", line 41, in async_setup
    flags.append(DEFAULT_FLAG)
AttributeError: 'str' object has no attribute 'append'

**Comment by J-Lindvig** [comment]
I will look into it later this evening.

**Comment by J-Lindvig** [comment]
Sorry for the delay.
I am unable to reproduce the error on my setup. Could ypu please provide me with a copy of your config?

/Jacob

**Comment by Wassini** [comment]
Very simple: 

flagdays_dk:
  time_offset: 10
  flags:
    Dannebrog

**Comment by Wassini** [comment]
Ok - found the "bug". I need to write it in  small letters :-)

**Comment by J-Lindvig** [comment]
OK, but I should have made it case insensitive, I will add it in an update.5. jul. 2022 14.58 skrev Lars Bo Wassini ***@***.***>:
Ok - found the "bug". I need to write it in  small letters :-)
