### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by Jinely8** [J-Lindvig/Flagdays_DK#6]
I have tried several times, installing it from the bottom, but I can't get the sensor up and running. I got following message in the log.
Logdetaljer (FEJL)

Logger: homeassistant.setup
Source: setup.py:288
First occurred: 1. november 2023 kl. 19.57.54 (1 occurrences)
Last logged: 1. november 2023 kl. 19.57.54

Error during setup of component flagdays_dk
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 288, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/flagdays_dk/__init__.py", line 104, in async_setup
    customFlagdays.update(flagdayFromSensor(customFlagday))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/flagdays_dk/__init__.py", line 65, in flagdayFromSensor
    attr_date_keys = list(attr_names.intersection(set(flagdayObj.attributes)))
                                                      ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'attributes'

H. Nymand

**Comment by Jinely8** [comment]
Hey. Still need help. Finally, I got the integration running - sort of. In other words, the only attributes the sensor picks up, are those listed in flagdays_dk.py. They got sorted, excluded. But all others, whether they are listed in config.yaml, or as sensors are ignored.   Anyone whos gotta clue???  I would be very grateful.
